In [ ]:
from deslib.des.des_knn import DESKNN
from sklearn import datasets
import numpy as np
import pandas as pd
import keras
from sklearn.ensemble import RandomForestClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.datasets import mnist
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.layers import Dense, BatchNormalization
import tensorflow as tf
from scikeras.wrappers import KerasClassifier
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from keras.models import load_model
from matplotlib import pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

## MNIST dataset
---

In [28]:
mnist_data = mnist.load_data()
(X, y), (X_test, y_test) = mnist_data
X, X_test = X / 255.0, X_test / 255.0
X = X.reshape(-1, 28*28)
X_test = X_test.reshape(-1, 28*28)
X_train, X_dsel, y_train, y_dsel = train_test_split(X, y, test_size=10000, random_state=42)
m = X_train.shape[0]
n = X_train.shape[1]

In [3]:
m, n

(50000, 784)

In [4]:
pool_of_classifiers = RandomForestClassifier(n_estimators=100, max_features='sqrt', n_jobs=-1, verbose=1)

In [5]:
pool_of_classifiers.fit(X_train, y_train)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    5.9s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:   15.8s finished


RandomForestClassifier(n_jobs=-1, verbose=1)

In [24]:
y_pred = pool_of_classifiers.predict(X_test[:5000])

[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 100 out of 100 | elapsed:    0.0s finished


In [25]:
accuracy_score(y_test[:5000], y_pred)

0.954

In [11]:
des_knn = DESKNN(pool_classifiers=pool_of_classifiers, DFP=False, with_IH=False, pct_accuracy=0.3, pct_diversity=0.3, n_jobs=-1)

In [12]:
des_knn.fit(X_dsel, y_dsel)

DESKNN(pct_accuracy=0.3,
       pool_classifiers=RandomForestClassifier(n_jobs=-1, verbose=1))

In [26]:
y_pred_des = des_knn.predict(X_test[:5000])

In [27]:
accuracy_score(y_test[:5000], y_pred_des)

0.9474

## Breast Cancer
---

In [70]:
from sklearn.datasets import load_breast_cancer
data = load_breast_cancer()
X = data.data
y = data.target

In [71]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [72]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=200 ,random_state=42)
X_dsel, X_test, y_dsel, y_test = train_test_split(X_test, y_test, test_size=50 ,random_state=42)

In [73]:
clf1 = RandomForestClassifier(n_estimators=400, max_features='sqrt', n_jobs=-1, verbose=1)

In [74]:
X.shape

(569, 30)

In [75]:
clf1.fit(X_train, y_train)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=-1)]: Done 184 tasks      | elapsed:    0.4s
[Parallel(n_jobs=-1)]: Done 400 out of 400 | elapsed:    1.0s finished


RandomForestClassifier(n_estimators=400, n_jobs=-1, verbose=1)

In [76]:
y_pred = clf1.predict(X_test)
accuracy_score(y_test, y_pred)

[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 184 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 400 out of 400 | elapsed:    0.0s finished


0.94

In [105]:
des_knn = DESKNN(pool_classifiers=clf1, DFP=False, k=10 ,with_IH=False, pct_accuracy=0.5, pct_diversity=0.3, n_jobs=-1, voting='hard')

In [106]:
des_knn.fit(X_dsel, y_dsel)

DESKNN(k=10,
       pool_classifiers=RandomForestClassifier(n_estimators=400, n_jobs=-1,
                                               verbose=1))

In [107]:
y_pred_des = des_knn.predict(X_test)
accuracy_score(y_test, y_pred_des)

0.98

In [104]:
from deslib.static import (StackedClassifier,
                           SingleBest,
                           StaticSelection,
                           Oracle)
oracle = Oracle(clf1).fit(X_train, y_train)
print('Oracle result: {}' .format(oracle.score(X_test, y_test)))

Oracle result: 1.0


In [108]:
dist, indx = des_knn.get_competence_region(query=X_test, k=10)

In [111]:
competence_region = indx

In [115]:
predictions = des_knn._predict_base(X_test)

In [116]:
predictions.shape

(50, 400)

In [161]:
predictions # predictions (class given to each sample by each base classifier) 

array([[1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [119]:
accuracy, diversity = des_knn.estimate_competence(competence_region=competence_region, distances=dist, predictions=predictions)

In [130]:
accuracy # shape would be -> (n_test_samples, n_base_clf)

array([[1. , 1. , 1. , ..., 1. , 1. , 1. ],
       [1. , 1. , 1. , ..., 0.9, 1. , 1. ],
       [1. , 1. , 1. , ..., 1. , 1. , 1. ],
       ...,
       [1. , 1. , 1. , ..., 1. , 1. , 1. ],
       [1. , 1. , 1. , ..., 1. , 0.9, 0.8],
       [0.9, 0.9, 1. , ..., 0.7, 0.9, 1. ]])

In [131]:
diversity # shape would be -> (n_test_samples, n_base_clf)

array([[  0. ,   0. ,   0. , ...,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. , ...,  -3.9,   0. ,   0. ],
       [  0. ,   0. ,   0. , ...,   0. ,   0. ,   0. ],
       ...,
       [  0. ,   0. ,   0. , ...,   0. ,   0. ,   0. ],
       [  0. ,   0. ,   0. , ...,   0. , -11.3, -15.6],
       [-28. , -28. ,   0. , ..., -33.1, -28. ,   0. ]])

In [146]:
selected_clf = des_knn.select(accuracy=accuracy, diversity=diversity)
print ("The shape of selected_clf - " , selected_clf.shape) # Shape = (n_test_samples, J)
# 400*0.3 = 120 classifier selcted for each query sample

The shape of selected_clf -  (50, 120)


In [154]:
selected_clf # The elements are the indices of classifiers in the pool which is selected for further voting for that query sample

array([[348, 189, 398, ...,  85,  84,  83],
       [341, 209, 164, ...,  80,  81, 104],
       [326, 193, 180, ...,  90,  88,  87],
       ...,
       [199, 188, 198, ...,  82,  81,  80],
       [343, 192, 213, ..., 368, 303, 366],
       [399,  71, 135, ..., 390,  17,  38]], dtype=int64)

In [158]:
probabilities = clf1.predict_proba(X_test)
probabilities

[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 184 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 400 out of 400 | elapsed:    0.0s finished


array([[0.0025, 0.9975],
       [0.985 , 0.015 ],
       [0.0125, 0.9875],
       [0.035 , 0.965 ],
       [0.005 , 0.995 ],
       [1.    , 0.    ],
       [0.0275, 0.9725],
       [0.3075, 0.6925],
       [0.    , 1.    ],
       [0.015 , 0.985 ],
       [1.    , 0.    ],
       [0.0025, 0.9975],
       [0.01  , 0.99  ],
       [0.    , 1.    ],
       [0.5325, 0.4675],
       [0.2   , 0.8   ],
       [0.0025, 0.9975],
       [0.    , 1.    ],
       [0.445 , 0.555 ],
       [0.    , 1.    ],
       [0.04  , 0.96  ],
       [0.0425, 0.9575],
       [0.67  , 0.33  ],
       [0.0525, 0.9475],
       [0.13  , 0.87  ],
       [0.0125, 0.9875],
       [0.6775, 0.3225],
       [0.995 , 0.005 ],
       [0.995 , 0.005 ],
       [0.1175, 0.8825],
       [0.065 , 0.935 ],
       [0.    , 1.    ],
       [0.035 , 0.965 ],
       [0.0625, 0.9375],
       [0.74  , 0.26  ],
       [0.025 , 0.975 ],
       [0.8625, 0.1375],
       [0.0025, 0.9975],
       [0.3925, 0.6075],
       [0.0375, 0.9625],


In [2]:
probabilities1 = des_knn.predict_proba(X_test)
probabilities1.shape

NameError: name 'des_knn' is not defined